[project]
name = "tz-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "../README.md"
requires-python = "==3.14.*"

dependencies = [
    "citiespy==0.6.13",
    "timezonefinder==8.2.0",
    "tzfpy==1.1.0",
    "pytest",
    "pytest-benchmark",
    "pytest-pretty",
]
